language: ruby
rvm:
- 2.0
- 2.1
env:
  - TEST_BRANCH=master
  - TEST_BRANCH=liquid-3
install: "travis_retry script/unbundle ; travis_retry script/bootstrap"
script: script/benchmark
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
